# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: auto_sign_pt

on:
  watch:
    types: [ started ]
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 23 * * *'
    # 国家时间 午夜12点 北京时间早上7点触发
jobs:
  pt_sign:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: pt_sign
        run: python run.py signin
        env:
          CONFIG: ${{ secrets.CONFIG }}
          QMSGAPI: ${{ secrets.QMSGAPI }}
          TGAPI: ${{ secrets.TGAPI }}
          CHATID: ${{ secrets.CHATID }}
